name: Build and Publish
on:
  push:
    branches:
    - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Build
      run: python -m pip install --user build
    - name: Build
      run: python -m build
